# This file was generated by GoReleaser. DO NOT EDIT.
class Eschargo < Formula
  desc "Escape Regex Metacharacters, made in Go."
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/p-rs/eschargo/releases/download/v0.4.0/eschargo_0.4.0_darwin_amd64.tar.gz"
    sha256 "c26d74e2ead58c1ba36a1bc3e939f124d691d9419f701bfd8c32643e522a6ef4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/p-rs/eschargo/releases/download/v0.4.0/eschargo_0.4.0_linux_amd64.tar.gz"
      sha256 "754a95ed0499b514d44235016709b16763f0ca6cc137cc9fc7fd71e24eb27740"
    end
  end

  def install
    bin.install "ecg"
  end
end
