# This file was generated by GoReleaser. DO NOT EDIT.
class Eschargo < Formula
  desc "Escape Regex Metacharacters, made in Go."
  homepage ""
  version "0.3.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/p-rs/eschargo/releases/download/v0.3.5/eschargo_0.3.5_darwin_amd64.tar.gz"
    sha256 "495a75c9827a349728cbaa6dfa9e87ae117d2f480102fea598334e2a359b269e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/p-rs/eschargo/releases/download/v0.3.5/eschargo_0.3.5_linux_amd64.tar.gz"
      sha256 "63f159d6c31cad7a39190d16e8ffc1ac9c5ea534c54281f3d70bb8b3c00d44a2"
    end
  end

  def install
    bin.install "ecg"
  end
end
