# This file was generated by GoReleaser. DO NOT EDIT.
class Eschargo < Formula
  desc "Escape Regex Metacharacters, made in Go."
  homepage ""
  version "0.3.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/p-rs/eschargo/releases/download/v0.3.3/eschargo_0.3.3_darwin_amd64.tar.gz"
    sha256 "aa1af20e70032e62f23309ad26b6cc94af3c365e448ab77d99f5220ca63e24be"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/p-rs/eschargo/releases/download/v0.3.3/eschargo_0.3.3_linux_amd64.tar.gz"
      sha256 "e23d24cf00764e1d52e3647ce6e53c1e2b1b53145fdd468caa7fb7bbbf507b18"
    end
  end

  def install
    bin.install "ecg"
  end
end
